FROM registry.fedoraproject.org/fedora:44

RUN dnf -y install mock rpm-build dnf-plugins-core rpmdevtools nano diffutils colordiff fish make
RUN dnf -y clean all

RUN cat >> /etc/dnf/dnf.conf <<-'EOF'
	[main]
	max_parallel_downloads=10
	fastestmirror=True
EOF

RUN cat >> /etc/mock/site-defaults.cfg <<-'EOF'
	config_opts['use_nspawn'] = False
	config_opts['isolation']  = 'simple'
	config_opts['use_bootstrap_image'] = True
	config_opts['plugin_conf']['root_cache_enable'] = True
	config_opts['plugin_conf']['yum_cache_enable']  = True
	config_opts['resultdir'] = '/work/out'
	config_opts['macros']['%_smp_mflags'] = '-j%{?_smp_build_ncpus}'
EOF

WORKDIR /work

CMD ["fish"]
